platform :ios, '7.0'

pod 'Bedrock/AutoLayout', :git => 'https://github.com/nickbolton/PBBedrock.git', :branch=>'master'
pod 'Bedrock/Emitter', :git => 'https://github.com/nickbolton/PBBedrock.git', :branch=>'master'

inhibit_all_warnings!

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGN_IDENTITY'] = 'iPhone Developer'
    end
  end
end
